liturgi:
	rm -rf out/
	mkdir out
	node liturgi-pdf.js ${MUSESCORE_BIN_PATH} ${HELLIGE_HALLVARD_NOTEBIBLIOTEK_PATH}/Liturgi out ${HELLIGE_HALLVARD_NOTEBIBLIOTEK_PATH}/PDF/Liturgi.pdf

individuelle-pdf:
	rm -rf ${HELLIGE_HALLVARD_NOTEBIBLIOTEK_PATH}/PDF
	mkdir ${HELLIGE_HALLVARD_NOTEBIBLIOTEK_PATH}/PDF
	node individuelle-pdf.js ${MUSESCORE_BIN_PATH} ${HELLIGE_HALLVARD_NOTEBIBLIOTEK_PATH} ${HELLIGE_HALLVARD_NOTEBIBLIOTEK_PATH}/PDF